[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pyright = "^1.1.371"
pulumi = "^3.124.0"
pulumi-aws = "^6.44.0"
pulumi-random = "^4.16.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"